Portfolio desktop version review
hagan199/my-portfolio pull request #6
Opened 2022-05-06 11:05 UTC by hagan199

#Portfolio desktop version. 
To make my portfolio responsive and to adopt to mobile framework and desktop as well.
1. Added contact-form.
2. Added contact  style.css.
3. Fix Linter error. 
4.  Added submit to be hover.
5. Update index.html;

2022-05-06 12:36 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @hagan199,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-06 12:36 UTC, Omar-Muhamad commented on assets/css/style.css
> +  background-color: rgb(252, 246, 246);
- [ ] Kindly add the correct path for the background image here to make it work online for this situation you can make it like that: `background-image: url('../background-desk.png');`
- [ ] Please remove the background color or make it white to match the Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/167130347-01aaeaa9-2330-4d4b-b336-3b517177368a.png) | ![image](https://user-images.githubusercontent.com/68796232/167130321-93f908e3-f83d-4584-a8ce-a8338882f43b.png)  |

2022-05-06 12:36 UTC, Omar-Muhamad commented on assets/css/style.css
> +  justify-content: center;
- [ ] Please add `margin: 0 auto;` after your width property to center the work cards to match the Figma design.
- [ ] Please increase the `row-gap` value to match the Figma design and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/167131403-ade6f460-5b0a-4259-b615-40255a729dcc.png) | ![image](https://user-images.githubusercontent.com/68796232/167131385-31dace70-282d-4375-ba2b-65a4b15511f5.png)  |

2022-05-06 12:36 UTC, Omar-Muhamad commented on assets/css/style.css
>  }
- [ ] Please add the correct font size, font-weight, and margins to these heading text and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/167132179-7a1cb746-d98f-4016-a33b-5f39c9839f0f.png)  |![image](https://user-images.githubusercontent.com/68796232/167132162-70c98e9a-5f8c-4456-9a63-cd4f5944cedb.png) |

2022-05-06 16:20 UTC, Ismailco commented
@hagan199,
I am reviewing your PR, normally I would invalidate it, but since the first reviewer give you a review I need to review it, please fix the linter errors and add a description to the PR as soon as possible so I can re-review your PR.

2022-05-06 16:41 UTC, Ismailco reviewed
Hi @hagan199,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that did not pass the linters and has no description in the PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-06 17:44 UTC, Ismailco requested changes
### Hi @hagan199,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 17:44 UTC, Ismailco commented on assets/css/style.css
> +  background-color: var(--white);
- [ ] [optional] Kindly change the background color of the body to ``` #E5E5E5 ``` so your design can be like the Figma one

![Screenshot_20220506_171133](https://user-images.githubusercontent.com/25227022/167180150-fc977173-68f6-46e9-aaa0-cd1722a19189.png)

2022-05-06 17:44 UTC, Ismailco commented on assets/css/style.css
> +.user-tool-d {
- [ ] As the previous reviewer suggests, please use the correct font size, and font-weight, for the ```Languages```, ```Frameworks```, ```Skills```  and try to stick as much as possible to the given Figma design.

![Screenshot_20220506_171033](https://user-images.githubusercontent.com/25227022/167182089-62457d35-7956-4042-86b1-b1ae11857c57.png)

2022-05-06 17:44 UTC, Ismailco commented on assets/css/style.css
> +  background-size: cover;
- [ ] [optional] You can use the ``` background-size: contain ``` to replicat the background from the Figma design

 - Figma Design:
 ![image](https://user-images.githubusercontent.com/68796232/167130347-01aaeaa9-2330-4d4b-b336-3b517177368a.png)

- Your Design:
![image](https://user-images.githubusercontent.com/68796232/167130321-93f908e3-f83d-4584-a8ce-a8338882f43b.png)

2022-05-06 17:44 UTC, Ismailco commented on assets/css/style.css
> +.btn-in {
- [ ] [optional] The elements of the form should be centered on the page including the ``` Get in touch``` button, please fix it

-Your design:
![Screenshot_20220506_174115](https://user-images.githubusercontent.com/25227022/167185887-a6e6d3ad-865f-4b8d-8835-96dfa90d9fb5.png)

-Figma design:
![Screenshot_20220506_174314](https://user-images.githubusercontent.com/25227022/167186287-e7d1fb98-4075-4523-8db2-0dab74be952f.png)

2022-05-06 19:14 UTC, prolajumokeoni approved these changes
Hi @

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a descriptive pull request message to your pull request to describe changes made in your  pull request

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 14:18 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @hagan199 ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
-No linter errors :+1: 
- Good use of GitHub flow :+1: 
- The app is working fine :+1: 

## Optional suggestions :small_airplane: 
- [OPTIONAL] Kindly make sure to use the current microverse README [template](https://github.com/microverseinc/readme-template) as required in the project.
- [OPTIONAL] In my opinion, it would be better to write a descriptive PR summary as it would make your project more professional
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 15:26 UTC, levy002 approved these changes
## Hello @hagan199 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly make sure to the [Microverse README template](https://github.com/microverseinc/readme-template) which will help you to keep your repo clean and more understandable. Please make sure to customize it according to your portfolio.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-10 09:17 UTC, merged